// Code generated by gnorm, DO NOT EDIT!

package nbsql_groups

import (
	"github.com/mwbrown/nagbot/db/nbsql"
	"github.com/pkg/errors"
)

// Row represents a row from 'groups'.
type Row struct {
	ID   int    // id (PK)
	Name string // name
}

// Field values for every column in Groups.
var (
	IDCol   nbsql.IntField    = "id"
	NameCol nbsql.StringField = "name"
)

// Query retrieves rows from 'groups' as a slice of Row.
func Query(db nbsql.DB, where nbsql.WhereClause) ([]*Row, error) {

	var sqlstr string
	var wherevals []interface{}

	const origsqlstr = `SELECT 
		id, name
		FROM public.groups`

	// Allow a nil WhereClause to select all rows.
	if where != nil {
		idx := 1
		sqlstr = origsqlstr + " WHERE (" + where.String(&idx) + ") "
		wherevals = where.Values()
	} else {
		sqlstr = origsqlstr
		wherevals = []interface{}{}
	}

	var vals []*Row

	q, err := db.Query(sqlstr, wherevals...)

	if err != nil {
		return nil, err
	}
	for q.Next() {
		r := Row{}
		err := q.Scan(&r.ID, &r.Name)
		if err != nil {
			return nil, err
		}
		vals = append(vals, &r)
	}
	return vals, nil
}

// One retrieve one row from 'groups'.
func One(db nbsql.DB, where nbsql.WhereClause) ([]*Row, error) {
	const origsqlstr = `SELECT 
		id, name
		FROM public.groups WHERE (`

	idx := 1
	sqlstr := origsqlstr + where.String(&idx) + ") "

	var vals []*Row
	q, err := db.Query(sqlstr, where.Values()...)
	if err != nil {
		return nil, err
	}
	for q.Next() {
		r := Row{}
		err := q.Scan(&r.ID, &r.Name)
		if err != nil {
			return nil, err
		}
		vals = append(vals, &r)
	}
	return vals, nil
}

// Insert inserts the row into the database.
func Insert(db nbsql.DB, r *Row) error {
	const sqlstr = `INSERT INTO groups (
			id, name
		) VALUES (
			$1, $2
		)`
	_, err := db.Exec(sqlstr, r.ID, r.Name)
	return errors.Wrap(err, "insert Groups")
}

// Update updates the Row in the database.
func Update(db nbsql.DB, r *Row) error {
	const sqlstr = `UPDATE groups SET (
			name		
		) = ( 
			$1
		) WHERE
			id = $2
		`
	_, err := db.Exec(sqlstr, r.Name, r.ID)
	return errors.Wrap(err, "update Groups:")
}

// Upsert performs an upsert for Groups.
//
// NOTE: PostgreSQL 9.5+ only
func Upsert(db nbsql.DB, r *Row) error {
	const sqlstr = `INSERT INTO groups (
		name, id
	) VALUES (
		$1, $2
	) ON CONFLICT (id) DO UPDATE SET (
		name
	) = ( 
		$1
	)`

	_, err := db.Exec(sqlstr, r.Name, r.ID)
	return errors.Wrap(err, "upsert Groups")
}

// Delete deletes the Row from the database.
func Delete(
	db nbsql.DB,
	id int,
) error {
	const sqlstr = `DELETE FROM groups WHERE id = $1`

	_, err := db.Exec(
		sqlstr,
		id,
	)
	return errors.Wrap(err, "delete Groups")
}
